Add search
Jarami/java-filmorate pull request #11
Opened 2024-12-08 00:35 UTC by FortovEgor

работу на БД не проверял (нет нужных таблиц в main), проверил базово (Spring запускается)

2024-12-08 07:21 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        SELECT f.film_id as "id"
Нет запятой после `"id"`

2024-12-08 07:21 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        SELECT f.film_id as "id"
Нет запятой после `"id"`

2024-12-08 07:25 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +               count(fl.film_id) as "rate"
Отсутствует группировка `GROUP BY f.film_id, fr.mpa_id`, без нее будет ошибка

2024-12-08 07:25 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +               count(fl.film_id) as "rate"
Отсутствует группировка `GROUP BY f.film_id, fr.mpa_id`, без нее будет ошибка. Можешь посмотреть, как это сделано в других запросах.

2024-12-08 10:35 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        SELECT f.film_id as "id"
не заметил, исправил

2024-12-08 10:35 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        SELECT f.film_id as "id"
fixed

2024-12-08 10:37 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +               count(fl.film_id) as "rate"
согласен, сначала написал через вложенный запрос, потом сделал короче, как у тебя, а группировку забыл, извиняюсь 
исправил

2024-12-08 10:37 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +               count(fl.film_id) as "rate"
fixed

2024-12-08 11:29 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +               count(fl.film_id) as "rate"
Тут есть один важный нюанс - у фильма может быть несколько режиссеров. Если мы возьмем фильм с двумя режиссерами, то count(fl.film_id) посчитает рейтинг, завышенный в 2 раза по сравнению с реальным. 
Убедиться можно на таком примере:
```sql
insert into directors (name) values ('Итан Коэл'), ('Джоэл Коэл');
insert into films (film_name, description, release_date, duration, mpa_id) values ('Старикам тут не место', 'ывы', '2007-01-06', 160, 1);
insert into films_directors (film_id, director_id) values (1, 1), (1, 2);
insert into users (user_name, email, login, birthday) values ('User 1', 'user1@mail.ru', 'user1', '2020-01-01');
insert into film_likes (film_id, user_id) values (1, 1);
```
Создаем фильм с двумя режиссерами и ставим фильму лайк. Вызываем:
```sql
        SELECT f.film_id as "id",
               fr.mpa_id as "mpa_id",
               count(fl.film_id) as "rate"
        FROM films AS f
        LEFT OUTER JOIN film_likes AS fl ON fl.film_id = f.film_id
        LEFT OUTER JOIN film_mpa AS fr ON f.mpa_id = fr.mpa_id
        LEFT OUTER JOIN films_directors AS fd ON f.film_id = fd.film_id
        LEFT OUTER JOIN directors AS d ON fd.director_id = d.director_id
        WHERE d.name LIKE('%Коэл%')
        group by f.film_id, fr.mpa_id
```
Получаем:
| id |mpa_id|rate|
|----|------|----|
| 1|     1|   2|

Чтобы такого не происходило, надо исправить count так `count(distinct fl.film_id)`

2024-12-08 11:47 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        SELECT f.film_id as "id",
Тут обязательно нужно вернуть `"film_id"` и `"film_name"`, а не `"id"` и `"name"`, потому что FilmRowMapper ожидает именно такие колонки.

2024-12-08 11:48 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        SELECT f.film_id as "id",
Также нужно вернуть `"film_id"` и `"film_name"`

2024-12-08 12:01 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        WHERE f.name LIKE("%:name%")
У таблицы `films` нет колонки `name`, есть `film_name`.

2024-12-08 12:13 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                    " UNION ALL " +
`UNION ALL` объединяет наборы. Т.е. ты можешь на выходе получить дубли одного и того же фильма. Лучше использовать `UNION` - он не возвращает дубли. Но я бы вместо этого написал бы другой запрос:
```sql
 SELECT f.film_id as "film_id",
        f.film_name as "film_name",
        f.description as "description",
        f.release_date as "release_date",
        f.duration as "duration",
        fr.mpa_id as "mpa_id",
        fr.mpa_name as "mpa_name",
        COUNT(DISTINCT fl.film_id) as "rate"
 FROM films AS f
 LEFT OUTER JOIN film_likes AS fl ON fl.film_id = f.film_id
 LEFT OUTER JOIN film_mpa AS fr ON f.mpa_id = fr.mpa_id
 LEFT OUTER JOIN films_directors AS fd ON f.film_id = fd.film_id
 LEFT OUTER JOIN directors AS d ON fd.director_id = d.director_id
 WHERE d.name LIKE :name OR f.film_name LIKE :name
 GROUP BY f.film_id, fr.mpa_id
 ORDER BY COUNT(DISTINCT fl.film_id)
 ```

2024-12-08 12:15 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        WHERE d.name LIKE("%:name%")
У меня это не сработало. В итоге сделал так:
```sql
WHERE d.name LIKE :name
```
и, соответственно, при формировании параметра:
```java
return namedTemplate.query(sqlQuery, Map.of("name", "%" + queryString + "%"), new FilmRowMapper());
```

2024-12-08 12:17 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +            case "title,director" -> FIND_FILMS_BY_FILM_AND_DIRECTOR_QUERY;
Для `""title,director"` и `"director,title"` запрос должен быть одинаковым. В итоге должен вернуться список фильмов, _отсортированный по рейтингу_.

2024-12-08 12:18 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        return namedTemplate.query(sqlQuery, Map.of("name", queryString), new FilmRowMapper());
Не надо забывать, что фильмам нужно добавить жанры. Как это сделать, можно посмотреть, например, в методе `getPopularFilms`.

2024-12-08 12:21 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.searchBy(queryString, searchBy);
Неплохо бы проверить searchBy на валидность. И если невалидно, то выбрасывать ошибку 400.

2024-12-08 12:30 UTC, Jarami requested changes
По уму, эту задачу следовало бы делать только после "Режиссеров". Но чтобы проверить работоспособность методов, можно сделать примерные таблицы:
```sql 
CREATE TABLE IF NOT EXISTS directors (
    director_id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS films_directors (
  film_id BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
  director_id INTEGER REFERENCES directors (director_id) ON DELETE CASCADE,
  PRIMARY KEY (film_id, director_id)
);
```
и работать с ними. После "Режиссеров" их придется изменить (а может и не придется, если ты договоришься с @zlov82). 
У меня в итоге заработали такие запросы
```sql
-- FIND_FILMS_BY_TITLE_QUERY
 SELECT f.film_id as "film_id",
        f.film_name as "film_name",
        f.description as "description",
        f.release_date as "release_date",
        f.duration as "duration",
        fr.mpa_id as "mpa_id",
        fr.mpa_name as "mpa_name",
        COUNT(DISTINCT fl.film_id) as "rate"
 FROM films AS f
 LEFT OUTER JOIN film_likes AS fl ON fl.film_id = f.film_id
 LEFT OUTER JOIN film_mpa AS fr ON f.mpa_id = fr.mpa_id
 WHERE LOWER(f.film_name) LIKE :name
 GROUP BY f.film_id, fr.mpa_id
 ORDER BY COUNT(DISTINCT fl.film_id)

-- FIND_FILMS_BY_DIRECTOR_QUERY
 SELECT f.film_id as "film_id",
        f.film_name as "film_name",
        f.description as "description",
        f.release_date as "release_date",
        f.duration as "duration",
        fr.mpa_id as "mpa_id",
        fr.mpa_name as "mpa_name",
        COUNT(DISTINCT fl.film_id) as "rate"
 FROM films AS f
 LEFT OUTER JOIN film_likes AS fl ON fl.film_id = f.film_id
 LEFT OUTER JOIN film_mpa AS fr ON f.mpa_id = fr.mpa_id
 LEFT OUTER JOIN films_directors AS fd ON f.film_id = fd.film_id
 LEFT OUTER JOIN directors AS d ON fd.director_id = d.director_id
 WHERE LOWER(d.name) LIKE :name
 GROUP BY f.film_id, fr.mpa_id
 ORDER BY COUNT(DISTINCT fl.film_id)

-- FIND_FILMS_BY_FILM_AND_DIRECTOR_QUERY (без UNION)
 SELECT f.film_id as "film_id",
        f.film_name as "film_name",
        f.description as "description",
        f.release_date as "release_date",
        f.duration as "duration",
        fr.mpa_id as "mpa_id",
        fr.mpa_name as "mpa_name",
        COUNT(DISTINCT fl.film_id) as "rate"
 FROM films AS f
 LEFT OUTER JOIN film_likes AS fl ON fl.film_id = f.film_id
 LEFT OUTER JOIN film_mpa AS fr ON f.mpa_id = fr.mpa_id
 LEFT OUTER JOIN films_directors AS fd ON f.film_id = fd.film_id
 LEFT OUTER JOIN directors AS d ON fd.director_id = d.director_id
 WHERE LOWER(d.name) LIKE :name OR LOWER(f.film_name) LIKE :name
 GROUP BY f.film_id, fr.mpa_id
 ORDER BY COUNT(DISTINCT fl.film_id)
```
**Важно**, что поиск не должен зависеть от регистра: в постановке используется пример с фильмом "Крадущийся тигр, затаившийся дракон", который должен находиться по "крад". Я в запросах использовал `LOWER`, т.е. при формировании параметра `name` тоже надо привести его к нижнему регистру:
```java
return namedTemplate.query(sqlQuery, Map.of("name", "%" + queryString.toLowerCase() + "%"), new FilmRowMapper());
```

2024-12-08 23:25 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +               count(fl.film_id) as "rate"
согласен, сделал тут в во втором запросе

2024-12-08 23:27 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        SELECT f.film_id as "id",
исправил

2024-12-08 23:28 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        SELECT f.film_id as "id",
+

2024-12-08 23:28 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        WHERE f.name LIKE("%:name%")
сделал

2024-12-08 23:30 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                    " UNION ALL " +
all убрал
вопросик - чем твой запрос лучше? он будет быстрее работать?

2024-12-08 23:32 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        WHERE d.name LIKE("%:name%")
сделал

2024-12-08 23:32 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +            case "title,director" -> FIND_FILMS_BY_FILM_AND_DIRECTOR_QUERY;
fixed

2024-12-08 23:33 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        return namedTemplate.query(sqlQuery, Map.of("name", queryString), new FilmRowMapper());
ты имеешь в виду, чтобы информация о жанрах и фильмах фигурировала в sql ответе?

2024-12-08 23:37 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.searchBy(queryString, searchBy);
сделал

2024-12-08 23:46 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        return namedTemplate.query(sqlQuery, Map.of("name", queryString), new FilmRowMapper());
Посмотри на getPopularFilms и другие. Там к фильмам подмешивается инфа о жанрах с помощью дополнительных запросов к БД

2024-12-08 23:48 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                    " UNION ALL " +
В общем-то ничем. Ты только проверь, что он выполняется без ошибок

2024-12-09 07:28 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.searchBy(queryString, searchBy);
Не увидел. Не забыл закомитить?

2024-12-09 14:30 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                    " ORDER BY f.film_id DESC";
В постановке сказано, что надо вернуть список фильмов, отсортированных по популярности. Это касается FIND_FILMS_BY_TITLE_QUERY, FIND_FILMS_BY_DIRECTOR_QUERY и FIND_FILMS_BY_FILM_AND_DIRECTOR_QUERY.

2024-12-09 14:31 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        return namedTemplate.query(sqlQuery, Map.of("name", "%" + queryString.toLowerCase() + "%"),
Добавить жанры

2024-12-09 14:32 UTC, Jarami requested changes
Не увидел некоторых изменений, про которые ты говорил. Не забыл запушить?

2024-12-10 00:42 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.searchBy(queryString, searchBy);
оно инкапсулировало внутри Storage, чтобы не дублировать код (см)

2024-12-10 00:45 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        return namedTemplate.query(sqlQuery, Map.of("name", queryString), new FilmRowMapper());
жанры сделал, режиссеров пока нет в Develop, я бы оттуда взял sql-запросы по ним + для тестов надо

2024-12-10 00:52 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                    " ORDER BY f.film_id DESC";
done

2024-12-10 00:52 UTC, FortovEgor commented
> Не увидел некоторых изменений, про которые ты говорил. Не забыл запушить?
прокомментил выше

2024-12-10 00:53 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        return namedTemplate.query(sqlQuery, Map.of("name", "%" + queryString.toLowerCase() + "%"),
если ты про вывод жанров, то сделал, директоров - жду develop

2024-12-10 10:24 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        return namedTemplate.query(sqlQuery, Map.of("name", "%" + queryString.toLowerCase() + "%"),
Ты в задаче про директоров ревьюер. Пока ты не одобришь ее, она в develop не попадет.

2024-12-12 07:47 UTC, Jarami reviewed
Не проходят постман-тесты. Проблема в маппером в DbFilmStorage::searchBy(описал ниже).

2024-12-12 07:47 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                    Map.of("filmId", film.getId()), new BeanPropertyRowMapper<>(Director.class));
BeanPropertyRowMapper использует переданный класс (здесь, Director.class) для маппинга данных из БД. В нашем случае его работа аналогична такому коду:
```java
public class SomeMapper implements RowMapper<Director> {
    @Override
    public Director mapRow(ResultSet rs, int rowNum) throws SQLException {
        return Director.builder()
                .id(rs.getInt("id"))
                .name(rs.getString("name"))
                .build();
    }
}
```
И это хорошо, нам не надо писать лишний код. Но проблема в том, что запрос `FIND_FILM_DIRECTORS_QUERY` не возвращает колонку `id`, он возвращает `director_id`. Решить проблему просто - надо использовать имеющийся маппер directorRowMapper. Т.е. код может выглядеть так:
```java
List<Director>  directors = namedTemplate.query(FIND_FILM_DIRECTORS_QUERY,
        Map.of("filmId", filmId), directorRowMapper);
```
А еще лучше воспользоваться методом `fillFilmsGenresAndDirectors`, который написал @zlov82 : 
```java
List<Film> films = findMany(sqlQuery, Map.of("name", "%" + queryString.toLowerCase() + "%"));

return fillFilmsGenresAndDirectors(films);
```

2024-12-12 08:37 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                    Map.of("filmId", film.getId()), new BeanPropertyRowMapper<>(Director.class));
тоооочно, спасибо!

2024-12-12 09:22 UTC, Jarami approved these changes

2024-12-12 09:42 UTC, Klasix12 approved these changes

2024-12-12 09:57 UTC, merged