Add director
Jarami/java-filmorate pull request #12
Opened 2024-12-09 20:02 UTC by zlov82

2024-12-09 20:20 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!sortBy.equalsIgnoreCase("year") && !sortBy.equalsIgnoreCase("likes")) {
Респект за проверку!

2024-12-10 10:21 UTC, Jarami requested changes
Все хорошо.
Единственное замечание, что нет валидации режиссера при создании. Остальные комментарии скорее информационные.

2024-12-10 10:21 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Director createDirector(@RequestBody Director newDirector) {
Тут нет валидации режиссера. У него не должно быть пустого имени (или имени целиком состоящих из пробелов).

2024-12-10 10:21 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return directorStorage.saveDirector(directorToSave);
Тут в метод можно подать непосредственно director'а. У него ведь не определен id.

2024-12-10 10:21 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            if (directors.isEmpty()) {
Здесь также можно вставить проверку, что указаны существующие режиссеры, как ты это сделал в `createFilm`. Можно даже эту проверку вынести в отдельный служебный метод.

2024-12-10 10:21 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (newFilmRequest.getDirectors() != null) {
Супер!

2024-12-10 10:21 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            @Qualifier("db") DirectorStorage directorStorage) {
Может быть лучше внедрить сюда DirectorService? Не настаиваю.

2024-12-10 10:21 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbDirectorStorage.java
> +    public List<Director> getById(List<Integer> directorIds) {
Чтобы не выгружать всех режиссеров, можно написать примерно так:
```java
    @Override
    public List<Director> getById(List<Integer> directorIds) {
        return findMany("SELECT * FROM directors WHERE director_id IN (:ids)", Map.of("ids", directorIds));
    }
```

2024-12-10 10:21 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        return getById(film.getId()).get();
В этом нет необходимости. Можно просто вернуть `film`.

2024-12-10 11:55 UTC, zlov82 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return directorStorage.saveDirector(directorToSave);
Уже переделал тип входящего параметра. 
Сам класс режиссера (или запрос нового режиссера из входящего параметра) не хочу передавать, так как никто не в теле запроса передать ID. тогда saveDirector пойдет по алгоритму update. А для обновления у нас есть PUT метод )

2024-12-10 12:27 UTC, zlov82 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            @Qualifier("db") DirectorStorage directorStorage) {
Сделано

2024-12-10 12:44 UTC, zlov82 commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        return getById(film.getId()).get();
Смотри, это относиться и обновлению и жанров и режиссеров:
на вход обновления приходит запрос со структурой режиссеров только с указанием id (без name)
мы доходим до этого блока кода, видим что в фильме на обновление film.getDirectors() != null - и пропускаем этап saveDirectors
и итоге у нас получается в ответе блок режиссеров будет такой же - как и пришёл в запросе на обновление - то есть без directors[].name

да, тут будет лишнее обращение к БД, но зато вернется корректиная структура ответа

2024-12-10 13:28 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        return getById(film.getId()).get();
![image](https://github.com/user-attachments/assets/c207f436-22df-40bc-b22f-e61d2a104418)

Также можно в этом убедиться, добавив логирование в метод `DbFilmStorage::save`:
```java
    log.info("film = {}", film);
    return getById(film.getId()).get();
}
```

2024-12-10 19:04 UTC, Jarami approved these changes

2024-12-10 22:35 UTC, zlov82 commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        return getById(film.getId()).get();
Вот такой запрос на создание фильмов 
`
{
	"name": "atnIsHCZ5dFkLuM",
	"description": "t3A6Nx4wHGhV6WDMqFaTjeIHsbvu2vwZGX8Wclpk556qd3Pysn",
	"releaseDate": "2000-09-17",
	"duration": 101,
	"mpa": {
		"id": 3
	},
	"genres": [],
	"directors": []
}
`
по твоему участку кода сохранения выдаст код ответа 404
на сколько это нормально - судить сейчас не могу.

но мой участок кода (в плане отсутствия режиссеров) пройдёт. но если мы будем возвращать film как он пришёл, то в ответе будет directors: null - что приводит к фейлу тестов постмана.

Решил данную проблему. Может быть костыльно, но пока сложно другое придумать.

2024-12-11 00:23 UTC, FortovEgor approved these changes

2024-12-11 14:14 UTC, merged