Add feed
Jarami/java-filmorate pull request #13
Opened 2024-12-10 00:01 UTC by FortovEgor

2024-12-10 09:22 UTC, Jarami requested changes
Я попробовал у себя локально сделать правки, которые указал и приложение стало отрабатывать без ошибок. Что в постмане, что юнит-тесты стали проходить.

2024-12-10 09:22 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmReviewService.java
> +        eventService.createReviewEvent(review.getUserId(), Operation.ADD, review.getReviewId());
Загвоздка в том, что `reviewId` будет определен только внутри метода `reviewStorage.save(review)`, а до него будет null (что вызовет ошибку). Т.е. должно быть примерно так:
```java
FilmReview r = reviewStorage.save(review);
eventService.createReviewEvent(r.getUserId(), Operation.ADD, r.getReviewId());
return r;
```
Также, если вдруг сохранение отзыва упадет с ошибкой, то событие о создании отзыва не сформируется (как и должно быть)

2024-12-10 09:22 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmReviewService.java
> +        eventService.createReviewEvent(oldReview.getUserId(), Operation.UPDATE, review.getReviewId());
Тут вполне можно использовать уже созданный `review`, а не `oldReview`, потому что тебе нужны только `userId` и `reviewId`, а они в этом методе не меняются. Аналогично замечанию из метода `createReview`, создание события нужно делать только после метода `save`.

2024-12-10 09:22 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmReviewService.java
> +        eventService.createReviewEvent(review.getUserId(), Operation.REMOVE, review.getReviewId());
На всякий случай, должно идти после `delete`.

2024-12-10 09:22 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        eventService.createAddFriendEvent(userId, friendId);
Метод `addFriend` возвращает успешность добавления в друзья. И создавать событие следует, только если добавление успешно, т.е. как-то так:
```java
boolean result = friendshipStorage.addFriend(user, friend);
if (result) {
    eventService.createAddFriendEvent(userId, friendId);
}
return result;
```

2024-12-10 09:22 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        eventService.createRemoveFriendEvent(userId, friendId);
Аналогично методу `addFriend`

2024-12-10 09:22 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbEventStorage.java
> +            update(
Вроде как нам не нужно обновление события. Эту ветку можно вырезать.

2024-12-10 09:22 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbEventStorage.java
> +                Map.of("userId", id), new BeanPropertyRowMapper<>(Event.class));
Тут лучше бы использовать EventRowMapper, который был определен в конструкторе. Т.е. сделать вот так:
```java
return findMany(FIND_EVENTS_BY_USER_ID_QUERY, Map.of("userId", id));
```
Дополнительно, это позволит избежать ошибки `Failed to instantiate [ru.yandex.practicum.filmorate.model.Event]: No default constructor found]`, потому что `BeanPropertyRowMapper` требует наличия дефолтного конструктора, а у Event его нет.

2024-12-10 09:22 UTC, Jarami commented on src/main/resources/schema.sql
> +CREATE TYPE operation_type AS ENUM ('remove', 'add', 'update');
Вот это классно!

2024-12-10 09:22 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private EventService eventService;
Тут нужно указать `final`. Тогда при наличии аннотации `@RequiredArgsConstructor`, lombok создаст конструктор такого вида:
```java
public UserController(UserService userService, EventService eventService) {
    this.userService = userService;
    this.eventService = eventService;
}
```
И таким образом, будут внедрены userService и eventService из контекста SpringBoot. А без этого eventService будет null (что вызовет ошибку в методе `getFeed`).

2024-12-10 09:22 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    public Long getEventId() {
Можно обойтись без `getEventId` и `setEventId`. Ты используешь аннотацию `@Getter` и `@Setter`, значит у тебя определены методы `getId` и `setId`. Их достаточно.

2024-12-10 09:22 UTC, Jarami commented on src/main/resources/schema.sql
> +    event_timestamp bigint NOT NULL,
Если бы это была реальная задача, то я бы тут использовал тип `TIMESTAMP`.

2024-12-10 09:22 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/EventRowMapper.java
> +                .operation(Operation.valueOf(resultSet.getString("operation")))
Тут будут ошибки, потому что в БД значения хранятся в нижнем регистре, а значит `EventType.valueOf` и `Operation.valueOf` ничего не найдут и упадут с ошибкой. Проще всего хранить EventType и Operation в БД в верхнем регистре и тогда тебе вообще не понадобится title у этих enum'ов.

2024-12-10 09:22 UTC, Jarami commented on src/main/resources/schema.sql
> +DROP TYPE IF EXISTS operation_type;
Тут можно дропать каскадно, т.е. так:
```sql
DROP TYPE IF EXISTS event_type CASCADE;
DROP TYPE IF EXISTS operation_type CASCADE;
```
Для упрощения жизни, в остальных таблицах можно сделать тоже самое.

2024-12-11 00:46 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmReviewService.java
> +        eventService.createReviewEvent(review.getUserId(), Operation.ADD, review.getReviewId());
исправил

2024-12-11 00:47 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmReviewService.java
> +        eventService.createReviewEvent(oldReview.getUserId(), Operation.UPDATE, review.getReviewId());
fixed

2024-12-11 00:47 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmReviewService.java
> +        eventService.createReviewEvent(review.getUserId(), Operation.REMOVE, review.getReviewId());
сделал

2024-12-11 00:48 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        eventService.createAddFriendEvent(userId, friendId);
fixed

2024-12-11 00:49 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbEventStorage.java
> +            update(
сделал

2024-12-11 00:50 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbEventStorage.java
> +                Map.of("userId", id), new BeanPropertyRowMapper<>(Event.class));
done

2024-12-11 00:50 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private EventService eventService;
сделал

2024-12-11 00:51 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    public Long getEventId() {
да, тупанул, извиняюсь

2024-12-11 00:52 UTC, FortovEgor commented on src/main/resources/schema.sql
> +    event_timestamp bigint NOT NULL,
сделал

2024-12-11 00:53 UTC, FortovEgor commented on src/main/resources/schema.sql
> +DROP TYPE IF EXISTS operation_type;
сделал

2024-12-11 00:56 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/EventRowMapper.java
> +                .operation(Operation.valueOf(resultSet.getString("operation")))
исправил в sql скрипте

2024-12-11 08:01 UTC, Jarami requested changes
При добавлении комитов в гитхабе упали юнит-тесты. И у меня, когда я скачал твою ветку и запустил юнит-тесты, они упали. 
Дело в том, что твои изменения типа колонки `events.event_timestamp` не применились. И у твоей локальной таблицы тип остался `BIGINT`. И в постмане всё работало. Однако юнит-тесты запускают новую БД, в которой тип колонки `events.event_timestamp` стал `TIMESTAMP` и тесты стали падать (потому что автоматической конвертации между `BIGINT` и `TIMESTAMP` в H2 нет). Ровно тоже самое произошло в гитхабе.
Тебе нужно добавить эту конвертацию (я в комментариях указал, где).

2024-12-11 08:01 UTC, Jarami commented on src/main/resources/schema.sql
> +DROP TYPE IF EXISTS operation_type CASCADE;
Нужно добавить `DROP TABLE IF EXISTS events CASCADE;` 
Таким образом, все изменения таблицы `events` применятся при перезапуске приложения.

2024-12-11 08:01 UTC, Jarami commented on src/main/resources/schema.sql
> +    event_timestamp timestamp NOT NULL,
Ты изменил тип колонки на `TIMESTAMP` и это хорошо. Но так как в команде создания таблицы написано `IF NOT EXISTS`, твои изменения не применились (т.е. таблица не пересоздалась). Чтобы применить изменения в нашем случае достаточно дропнуть ее (см. замечание выше). Если бы это было реальное приложение, то нужно было бы писать скрипт мутации колонки.

2024-12-11 08:01 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbEventStorage.java
> +                            "event_timestamp", event.getTimestamp(),
`event.timestamp` имеет тип `long`, а колонка `event_timestamp` - `TIMESTAMP`. Автоматической конвертации между ними (по крайней мере в H2) нет. Поэтому нужно в этой строке написать примерно так:
```java
"event_timestamp", Timestamp.from(Instant.ofEpochMilli(event.getTimestamp())),
```

2024-12-11 08:01 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/EventRowMapper.java
> +                .timestamp(resultSet.getLong("event_timestamp"))
`event.timestamp` имеет тип `long`, а колонка `event_timestamp` - `TIMESTAMP`. Автоматической конвертации между ними (по крайней мере в H2) нет. Поэтому нужно в этой строке написать примерно так:
```java
.timestamp(resultSet.getTimestamp("event_timestamp").toInstant().toEpochMilli())
```

2024-12-11 19:13 UTC, FortovEgor commented on src/main/resources/schema.sql
> +DROP TYPE IF EXISTS operation_type CASCADE;
сделал

2024-12-11 19:15 UTC, FortovEgor commented on src/main/resources/schema.sql
> +    event_timestamp timestamp NOT NULL,
сделал

2024-12-11 19:18 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbEventStorage.java
> +                            "event_timestamp", event.getTimestamp(),
сделал

2024-12-11 19:18 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/EventRowMapper.java
> +                .timestamp(resultSet.getLong("event_timestamp"))
done

2024-12-12 06:42 UTC, Jarami approved these changes

2024-12-12 09:09 UTC, Klasix12 approved these changes

2024-12-12 09:25 UTC, merged