Получение общих фильмов
Jarami/java-filmorate pull request #5
Opened 2024-12-04 19:51 UTC by Klasix12

2024-12-05 06:48 UTC, Jarami requested changes
Все хорошо. Нужно еще добавить проверку на существование пользователей и можно сливать ветки.

2024-12-05 06:48 UTC, Jarami commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userId == null || friendId == null) {
Очень хотелось бы иметь тут проверку, что такие пользователи существуют. Для этого понадобится внедрить в этот класс UserService и вызвать у него метод getUserById() для каждого id.

2024-12-05 15:07 UTC, Jarami approved these changes

2024-12-08 00:36 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +            INNER JOIN film_mpa fr ON f.mpa_id = fr.mpa_id
INNER? если у фильма нет рейтинга, то он не попадет в выборку :(

2024-12-08 18:15 UTC, zlov82 approved these changes
Всё хорошо

2024-12-09 13:33 UTC, merged